name: Test
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'repo-sync/**'
      - "main"
      - "master"
  pull_request:
    branches-ignore:
      - 'repo-sync/**'
  schedule:
    - cron: "16 0 * * 0"

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
        - name: Hello World
          uses: gr2m/hello-world-js-action@v1