name: Test
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "repo-sync/**"
      - "main"
      - "master"
  pull_request:
    branches-ignore:
      - "repo-sync/**"
  schedule:
    - cron: "16 0 * * 0"

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"